[package]
name = "sd-p2p-proto"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
ed25519-dalek = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
uuid = { workspace = true }
