[package]
authors = ["Jamie Pine <jamie@spacedrive.com>"]
edition = "2021"
name    = "task-validator"
version = "0.1.0"

[dependencies]
chrono      = "0.4"
clap        = { version = "4.5", features = ["derive"] }
comfy-table = "7.1"
glob        = "0.3"
jsonschema  = "0.17"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
serde_yaml  = "0.9"
