[package]
name = "sd-mobile-core"
version = "0.1.0"
rust-version = "1.64.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
once_cell = "1.18.0"
sd-core = { path = "../../../../../core", features = [
	"mobile",
], default-features = false }
rspc = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
futures = "0.3.28"
tracing = { workspace = true }
futures-channel = "0.3.28"
futures-locks = "0.7.1"
