[package]
name = "prisma-cli"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
sd-sync-generator = { path = "../sync-generator" }

prisma-client-rust-cli = { workspace = true }
