[package]
name = "prisma-cli"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
# Spacedrive Sub-crates
sd-sync-generator = { path = "../sync-generator" }

# Workspace dependencies
prisma-client-rust-cli = { workspace = true }
