[package]
name    = "prisma-cli"
version = "0.1.0"

edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-sync-generator = { path = "../sync-generator" }

# Specific prisma-cli dependencies
[dependencies.prisma-client-rust-generator]
default-features = false
features         = ["migrations", "specta", "sqlite", "sqlite-create-many"]
git              = "https://github.com/spacedriveapp/prisma-client-rust.git"
rev              = "9d14e55e1d"
