[package]
name = "sd-sync-example"
version = "0.1.0"
rust-version = "1.75.0"
publish = false
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
axum = { workspace = true }
rspc = { workspace = true, features = ["axum"] }
tokio = { workspace = true, features = ["full"] }
prisma-client-rust = { workspace = true }
dotenv = "0.15.0"
tower-http = { version = "0.3.4", features = ["cors"] }
sd-sync = { path = ".." }
uuid = { workspace = true, features = ["v4"] }
http = "0.2.8"
