[package]
name = "sd-sync-example"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
publish = false

[dependencies]
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }
axum = "0.6.4"
rspc = { workspace = true, features = ["axum"] }
tokio = { version = "1.21.2", features = ["full"] }
prisma-client-rust = { workspace = true }
dotenv = "0.15.0"
tower-http = { version = "0.3.4", features = ["cors"] }
sd-sync = { path = ".." }
uuid = { version = "1.1.2", features = ["v4"] }
http = "0.2.8"
