[package]
name = "sd-desktop-windows"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
libc = { workspace = true }
normpath = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.57"
features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"]
