[package]
name = "sd-desktop-windows"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
normpath = { workspace = true }
thiserror = { workspace = true }
libc = "0.2"
winapi = "0.3.9"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.51"
features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_System_Com"]
