blank_issues_enabled: false
contact_links:
  - name: :pray: Get Help
    url: https://github.com/spacedriveapp/spacedrive/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: ðŸ’¡ Feature Request
    url: https://github.com/spacedriveapp/spacedrive/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: ðŸ’¬ Discord Chat
    url: https://discord.gg/gTaF2Z44f5
    about: Ask questions and talk to other Spacedrive users and the maintainers
