[package]
name = "sd-sync"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
specta = { workspace = true, features = ["uuid", "uhlc"] }
serde = "1.0.188"
serde_json = { workspace = true }
uhlc = "=0.5.2"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
prisma-client-rust = { workspace = true }
