[package]
name = "sd-mobile-android"
version = "0.1.0"
rust-version = "1.64"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lib]
# Android can use dynamic linking since all FFI is done via JNI
crate-type = ["cdylib"]

[dependencies]
# Spacedrive Sub-crates
sd-mobile-core = { path = "../../core" }

# Workspace dependencies
tracing = { workspace = true }

# Specific Mobile Android dependencies
jni = "0.21.1"
