[package]
name = "sd-mobile-android"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

[lib]
# Android can use dynamic linking since all FFI is done via JNI
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
# FFI
jni = "0.19.0"

# Core mobile handling stuff
sd-mobile-core = { path = "../core", features = ["android"] }

# Other 
tracing = "0.1.37"
