[package]
edition = "2021"
name    = "spacedrive-cli"
version = "0.1.0"

[dependencies]
anyhow          = "1"
bincode         = "1"
serde           = { version = "1", features = ["derive"] }
serde_json      = "1"
spacedrive-core = { path = "../../core" }
tokio           = { version = "1", features = ["full"] }
uuid            = { version = "1", features = ["serde", "v4"] }
