[package]
name = "sd-client"
version = "0.1.0"
edition = "2021"

[dependencies]
sd-core = { path = "../../core" }
tokio = { version = "1", features = ["net", "io-util", "rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
