[package]
name = "sd-p2p-block"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-p2p = { path = "../../" }
sd-p2p-proto = { path = "../proto" }

# Workspace dependencies
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
