[package]
name = "notify"
version = "6.1.1"
rust-version = "1.63"
description = "Cross-platform filesystem notification library"
documentation = "https://docs.rs/notify"
homepage = "https://github.com/notify-rs/notify"
repository = "https://github.com/notify-rs/notify.git"
readme = "../README.md"
license = "CC0-1.0"
keywords = ["events", "filesystem", "notify", "watch"]
categories = ["filesystem"]
authors = [
  "FÃ©lix Saparelli <me@passcod.name>",
  "Daniel Faust <hessijames@gmail.com>",
  "Aron Heinecke <Ox0p54r36@t-online.de>"
]

edition = "2021"

[dependencies]
crossbeam-channel = { version = "0.5.0", optional = true }
filetime = "0.2.22"
libc = "0.2.4"
log = "0.4.17"
serde = { version = "1.0.89", features = ["derive"], optional = true }
walkdir = "2.2.2"
tracing = { workspace = true }
tokio = { workspace = true }

[target.'cfg(any(target_os="linux", target_os="android"))'.dependencies]
inotify = { version = "0.10", default-features = false }
mio = { version = "0.8", features = ["os-ext"] }

[target.'cfg(target_os="macos")'.dependencies]
bitflags = "2.3.0"
fsevent-sys = { version = "4", optional = true }
kqueue = { version = "1.0", optional = true }
mio = { version = "0.8", features = ["os-ext"], optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_WindowsProgramming", "Win32_System_IO"] }

[target.'cfg(any(target_os="freebsd", target_os="openbsd", target_os = "netbsd", target_os = "dragonflybsd", target_os = "ios"))'.dependencies]
kqueue = "^1.0.4" # fix for #344
mio = { version = "0.8", features = ["os-ext"] }

[dev-dependencies]
serde_json = "1.0.39"
tempfile = "3.2.0"
nix = "0.23.1"

[features]
default = ["macos_fsevent","crossbeam-channel"]
timing_tests = []
manual_tests = []
macos_kqueue = ["kqueue", "mio"]
macos_fsevent = ["fsevent-sys"]
