[package]
name = "sdcore-lib"
version = "0.1.0"
edition = "2021"
rust-version = "1.63.0"

[lib]
name = "sdcore"
crate-type = ["staticlib", "cdylib"] # staticlib for IOS and cdylib for Android

[dependencies]
once_cell = "1.13.0"
sdcore = { path = "../../../core", features = ["mobile", "p2p"], default-features = false }
serde_json = "1.0.83"
tokio = "1.20.1"
openssl = { version = "0.10.41", features = ["vendored"] } # Override features of transitive dependencies

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"
objc_id = "0.1.1"
objc-foundation = "0.1.1"

# This is `not(ios)` instead of `android` because of https://github.com/mozilla/rust-android-gradle/issues/93
[target.'cfg(not(target_os = "ios"))'.dependencies]
jni = "0.19.0"
