name: Build ffmpeg windows

permissions: read-all

on:
  push:
    paths:
      - .github/workflows/ffmpeg-windows.yml
      - .github/scripts/ffmpeg-windows/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/ffmpeg-windows.yml
      - .github/scripts/ffmpeg-windows/**
  # trunk-ignore(yamllint/empty-values)
  workflow_dispatch:

# Cancel previous runs of the same workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FFMPEG_VERSION: "6.0"

jobs:
  build-ffmpeg-windows:
    name: Build ffmpeg for windows
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          platforms: linux/amd64
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build ffmpeg
        run: |
          set -euxo pipefail
          cd .github/scripts/ffmpeg-windows
          docker build --build-arg FFMPEG_VERSION=$FFMPEG_VERSION -o . .

      - name: Publish ffmpeg x86_64
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ env.FFMPEG_VERSION }}-x86_64
          path: .github/scripts/ffmpeg-windows/dlls/*
          if-no-files-found: error
