name: Release

on:
  workflow_dispatch:

# NOTE: For Linux builds, we can only build with Ubuntu. It should be the oldest base system we intend to support. See PR-759 & https://tauri.app/v1/guides/building/linux for reference.

jobs:
  desktop-main:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            bundles: dmg
          - host: macos-latest
            target: aarch64-apple-darwin
            bundles: dmg
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi
          # - host: windows-latest
          #   target: aarch64-pc-windows-msvc
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bundles: deb,appimage
          # - host: ubuntu-20.04
          #   target: x86_64-unknown-linux-musl
          # - host: ubuntu-20.04
          #   target: aarch64-unknown-linux-gnu
          # - host: ubuntu-20.04
          #   target: aarch64-unknown-linux-musl
          # - host: ubuntu-20.04
          #   target: armv7-unknown-linux-gnueabihf
    name: Desktop - Main ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js, pnpm and dependencies
        uses: ./.github/actions/setup-pnpm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup System and Rust
        uses: ./.github/actions/setup-system
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          targets: ${{ matrix.settings.target }}

      - name: Build
        run: |
          pnpm desktop build --ci -v --target ${{ matrix.settings.target }} --bundles ${{ matrix.settings.bundles }},updater
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Publish Artifacts
        uses: ./.github/actions/publish-artifacts
        with:
          target: ${{ matrix.settings.target }}
          profile: release
